// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqeqezvgodogwhikhjqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xZXFlenZnb2RvZ3doaWtoanF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTAwODUsImV4cCI6MjA2MzcyNjA4NX0.rWaz6iOBAp-cdC4coJHY16scJPuAoTpMEXPqNaMOLsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);